### ISSUE TITLE
Module not found: Error: Must provide valid GraphQLSchema

### ISSUE THREAD

**Issue by blacklakeDev** [danielholmes/relay-compiler-webpack-plugin#16]
when I use the relay-compiler to compile against the schema, it's alright. but build with this plugin in webpack,  it throws this error

**Comment by danielholmes** [comment]
@blacklakeDev I'm going to need more information to look into this. e.g. your webpack build, the full error stack trace, etc. 

I've run into validation issues before when there are multiple versions of graphql in your node_modules. One of the validation steps (can't find a reference for it atm) checks against a GraphQL schema class. If part of your application creates a GraphQL schema from one version of graphql then another version of graphql won't validate it. It could be your issue - maybe try listing your dependencies to find out if there are multiple versions of graphql being installed, or try installing your dependencies as flat

**Comment by simenbrekken** [comment]
@blacklakeDev I ran into the same issue, and it is probably as @danielholmes says. Make sure you only have one version of the `graphql` package installed. You can verify this by running `find node_modules -name graphql` in your project directory. Most likely you'll see the following:

- node_modules/relay-compiler/node_modules/graphql
- node_modules/babel-plugin-relay/node_modules/graphql
- node_modules/graphql

Deleting node_modules/relay-compiler/node_modules/graphql fixed it.

**Comment by danielholmes** [comment]
Have released a new version which removes graphql explicit dependency which will hopefully fix this issue going forward (https://github.com/danielholmes/relay-compiler-webpack-plugin/releases/tag/v0.6.0)
