### ISSUE TITLE
throwing errors causes the build to hang

### ISSUE THREAD

**Issue by graingert** [danielholmes/relay-compiler-webpack-plugin#17]

**Comment by graingert** [comment]
I upgraded to graphql 0.12 and this caused relay-compiler to fail because of a version conflict. This is expected. However instead of the build halting it just hung after printing the error.

**Comment by danielholmes** [comment]
Fixed in [v1.0.0](https://github.com/danielholmes/relay-compiler-webpack-plugin/releases/tag/v1.0.0)
