### ISSUE TITLE
Alternative to the GraphQL peer dependency version gotcha

### ISSUE THREAD

**Issue by astorije** [danielholmes/relay-compiler-webpack-plugin#20]
Hi there!

First of, thanks a lot for this plugin! It's a real pleasure to not have to run `relay-compiler` by hand (especially when using `webpack-dev-server`).

I just fell into the [GraphQL version gotcha](https://github.com/danielholmes/relay-compiler-webpack-plugin#gotchas) and was wondering why this was an issue. So let me start by acknowledging that I do not have the full context for this, apologies if I make the wrong assumptions.

It seems to me that the only required peer dependencies are `webpack` and `relay-compiler`. I may be missing something, but why is `graphql` a peer dependency?
After all, if the same version of `graphql` than the one used by `relay-compiler` is required, relying on `relay-compiler`'s `graphql` own dependency should be enough, no?

Thanks!

**Comment by danielholmes** [comment]
@astorije Good question. Currently we import types from graphql so we are using it, but as you say it will be pulled in anyway. There's another similar case where we're using immutable but don't explicitly include it ourselves (it comes in via relay-compiler):

https://github.com/danielholmes/relay-compiler-webpack-plugin/blob/master/src/getWriter.js#L3

I haven't thought on this too deeply but I can see it both ways. I think it's bad practice to implicitly rely on packages to pull in other packages. But in a practical sense constraining relay-compiler to versions where we can be sure of its dependencies plus the need to work around graphql requiring only one version, maybe it's best to just ditch it.

I'll think on it a bit. Any extra input would be appreciated

**Comment by astorije** [comment]
That's a good write-up, @danielholmes, thanks for the answer!

I understand what you mean re: bad practice to implicitly rely on packages, but in this particular case, the version constraint makes this a bit particular. I had a build failing and couldn't figure out why, until I realized there was this constraint.

I [maintain a plugin for Chai](https://github.com/astorije/chai-immutable) that requires a peerDependency to Chai, and had a similar issue. The plugin essentially has to be compatible with all versions it supports. That was all good and well for Chai v2 and v3, but v4 broke stuff, and I am in a situation where the plugin is either compatible with Chai v3 or v4, but not both. If I wanted to do so, I could probably introspect and detect the version at runtime, but I don't think we'll go with that.

An alternative to removing the peerDependency in your case would be to make the plugin agnostic of the `graphql` version, i.e. plugin would work with whichever version. I haven't looked at your codebase, would that be doable?

**Comment by danielholmes** [comment]
@astorije I've removed it now. Thanks for pointing this out and your thoughts

**Comment by astorije** [comment]
Awesome, thanks @danielholmes! I confirmed it's still works on my end, and the warning disappeared.
Now I hope I didn't point you to an even worse situation! :)

Thanks for your hard work 🙏
