### ISSUE TITLE
Add option to not output generated files

### ISSUE THREAD

**Issue by jquense** [danielholmes/relay-compiler-webpack-plugin#26]
Hey there, thanks for the great plugin! Would you be open to adding an option to not actually write out the compiled files to disk? Webpack in it's infinite extensibility allows for wrapping the file system used to resolve and write files whereever you want including in-memory.

We do this in https://github.com/4Catalyzer/css-literal-loader which extracts tagged templates into a "virtual file" and replaced by a `require` to said virtual file. The magic is all in https://github.com/4Catalyzer/css-literal-loader/blob/master/src/VirtualModulePlugin.js I'd be happy to throw together a PR if it's something you'd think you'd add

**Comment by danielholmes** [comment]
@jquense I'd be open to it, however... The file writing is currently handled by the relay-compiler package [Ref 1](https://github.com/facebook/relay/blob/master/packages/relay-compiler/codegen/RelayFileWriter.js) [Ref 2](https://github.com/facebook/relay/blob/master/packages/relay-compiler/codegen/writeRelayGeneratedFile.js) [Ref3](https://github.com/facebook/relay/blob/master/packages/relay-compiler/graphql-compiler/codegen/CodegenDirectory.js) and it includes a fair amount of extra work in the writer. 

To consider a PR I'd want some interaction with the relay-compiler FileWriter that wouldn't be much work to maintain every time the relay-compiler file writing changes. e.g. I know it's inefficient, but maybe still write the files to disk using the FileWriter to some tmp directory then read them back into memory for your purposes. 

Another (better IMO) option is to pursue the changes with the relay-compiler package directly and thread the `memory-fs` through FileWriter -> writeRelayGeneratedFile -> CodegenDirectory as an optional dependency that defaults to `fs`.

**Comment by danielholmes** [comment]
Closing because not pursued by OP
