### ISSUE TITLE
Support TypeScript

### ISSUE THREAD

**Issue by koddsson** [danielholmes/relay-compiler-webpack-plugin#33]
Hey hey @danielholmes 👋 

I'm wondering if we can support TypeScript in `relay-compiler-webpack-plugin`? I've been poking around and it seems like [`relay-compiler` now supports multiple languages](https://github.com/facebook/relay/pull/2293) and this has spawned [`relay-compiler-language-typescript`](https://github.com/relay-tools/relay-compiler-language-typescript).

I looked at the source and tried to debug a bit but can't seem to figure it out right now. I think we are hardcoding js as a parser config in the codebase and this should now be dynamic depending on the `language` options key.

I'm more then willing to work on this and I'll be looking at this more soon but I figured I'd open this up in case you'd have any good ideas on how we can do this.

**Comment by danielholmes** [comment]
Yea I'm happy to support this, I noticed they were setting up for multiple language support last time I was poking around too.

First steps I can do are some refactors so we reference the JS language module that relay-compiler provides (a bunch of that stuff is hardcoded here atm such as file extensions). From what I can see, the [RelayCompilerBin](https://github.com/facebook/relay/blob/master/packages/relay-compiler/bin/RelayCompilerBin.js) is a good reference point - it basically performs the same function as we do of setting up + configuring the relay compiler.

But when it comes to checking it works with other languages, I'll need some help. I have zero experience with typescript and don't have the motivation or time right now to learn it

**Comment by koddsson** [comment]
Cool! No worries, I can do the TypeScript testing and come configuring and hopefully some of the work as well 🙆‍♂️

**Comment by danielholmes** [comment]
@koddsson There's a languagePlugin option now available in both v1.0.2 and v2.0.0-rc.2 . Let me know if you run in to any troubles using it with typescript

**Comment by koddsson** [comment]
I think we are good here, thanks for the help ✨
