### ISSUE TITLE
Upcoming relay changes that will affect this plugin

### ISSUE THREAD

**Issue by jquense** [danielholmes/relay-compiler-webpack-plugin#46]
Hey there 👋 Just wanted to give you a heads up that there are two changes in the pipe upstream, aimed at making integration better for webpack. I'm planning on sending a PR mkaing use of the changes, but thought it'd be neighborly to give you a heads up.

- https://github.com/facebook/relay/pull/2838
- https://github.com/facebook/relay/pull/2837

In particular the output change means, as is, the plugin won't write anything out now, since the changes go through the reporter. Hopefully this is a good thing tho since we can actually pipe those messages into webpack directly and let folks using webpack output plugins handle them.

The filesystem PR should give the opportunity to use webpacks fs wrapper which is heavily cached, should cut down on IO from disk and give a small speed improvement (hopefully)

**Comment by danielholmes** [comment]
@jquense Thanks for this. I'm a bit busy right now, but can probably get to this some time next week

**Comment by taion** [comment]
I think we can close this out now.
